ALTER TABLE developers ADD salary INT DEFAULT 500;
UPDATE developers SET salary = 1000 WHERE name = 'Ivanov';
UPDATE developers SET salary = 1500 WHERE name = 'Petrov';
UPDATE developers SET salary = 3000 WHERE name = 'Sidorov';
UPDATE developers SET salary = 5000 WHERE name = 'Sushko';
UPDATE developers SET salary = 1200 WHERE name = 'Radko';
UPDATE developers SET salary = 3500 WHERE name = 'Dzubenko';
UPDATE developers SET salary = 1000 WHERE name = 'Sadko';
UPDATE developers SET salary = 2500 WHERE name = 'Golovko';
UPDATE developers SET salary = 2000 WHERE name = 'Buchak';